/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { BigNumberish } from 'ethers/utils';

export class TransactionOverrides {
  nonce?: BigNumberish | Promise<BigNumberish>;
  gasLimit?: BigNumberish | Promise<BigNumberish>;
  gasPrice?: BigNumberish | Promise<BigNumberish>;
  value?: BigNumberish | Promise<BigNumberish>;
  chainId?: number | Promise<number>;
}

export { Gatekeeper } from './Gatekeeper';
export { TokenCapacitor } from './TokenCapacitor';
export { ParameterStore } from './ParameterStore';
export { BasicToken } from './BasicToken';
