/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from 'ethers';
import { Provider } from 'ethers/providers';
import { BigNumber } from 'ethers/utils';
import { TransactionOverrides } from '.';

export class ParameterStore extends Contract {
  functions: {
    params(arg0: string): Promise<string>;

    get(_name: string): Promise<string>;

    getAsUint(_name: string): Promise<BigNumber>;

    getAsAddress(_name: string): Promise<string>;

    init(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    setInitialValue(
      _name: string,
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {
    ParameterSet(key: null, value: null): EventFilter;
  };
}
