/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from 'ethers';
import { Listener, Provider } from 'ethers/providers';
import { Arrayish, BigNumber, BigNumberish, Interface } from 'ethers/utils';
import { TransactionOverrides, TypedEventDescription, TypedFunctionDescription } from '.';

interface TimeTravelingGatekeeperInterface extends Interface {
  functions: {
    getWinningSlate: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    depositVoteTokens: TypedFunctionDescription<{
      encode([numTokens]: [BigNumberish]): string;
    }>;

    slateRequests: TypedFunctionDescription<{
      encode([slateID]: [BigNumberish]): string;
    }>;

    withdrawVoteTokens: TypedFunctionDescription<{
      encode([numTokens]: [BigNumberish]): string;
    }>;

    withdrawStake: TypedFunctionDescription<{
      encode([slateID]: [BigNumberish]): string;
    }>;

    contestSlates: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    delegateVotingRights: TypedFunctionDescription<{
      encode([_delegate]: [string]): string;
    }>;

    getFirstChoiceVotes: TypedFunctionDescription<{
      encode([epochNumber, resource, slateID]: [BigNumberish, string, BigNumberish]): string;
    }>;

    requestPermission: TypedFunctionDescription<{
      encode([metadataHash]: [Arrayish]): string;
    }>;

    finalizeContest: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    voteTokenBalance: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    donateChallengerStakes: TypedFunctionDescription<{
      encode([epochNumber, resource, startIndex, count]: [
        BigNumberish,
        string,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    commitBallot: TypedFunctionDescription<{
      encode([voter, commitHash, numTokens]: [string, Arrayish, BigNumberish]): string;
    }>;

    recommendSlate: TypedFunctionDescription<{
      encode([resource, requestIDs, metadataHash]: [string, (BigNumberish)[], Arrayish]): string;
    }>;

    didCommit: TypedFunctionDescription<{
      encode([epochNumber, voter]: [BigNumberish, string]): string;
    }>;

    revealBallot: TypedFunctionDescription<{
      encode([epochNumber, voter, resources, firstChoices, secondChoices, salt]: [
        BigNumberish,
        string,
        (string)[],
        (BigNumberish)[],
        (BigNumberish)[],
        BigNumberish
      ]): string;
    }>;

    requestCount: TypedFunctionDescription<{ encode([]: []): string }>;

    delegate: TypedFunctionDescription<{ encode([]: [string]): string }>;

    ballots: TypedFunctionDescription<{ encode([]: [BigNumberish]): string }>;

    getSecondChoiceVotes: TypedFunctionDescription<{
      encode([epochNumber, resource, slateID]: [BigNumberish, string, BigNumberish]): string;
    }>;

    currentEpochNumber: TypedFunctionDescription<{ encode([]: []): string }>;

    stakeTokens: TypedFunctionDescription<{
      encode([slateID]: [BigNumberish]): string;
    }>;

    startTime: TypedFunctionDescription<{ encode([]: []): string }>;

    didReveal: TypedFunctionDescription<{
      encode([epochNumber, voter]: [BigNumberish, string]): string;
    }>;

    COMMIT_PERIOD_START: TypedFunctionDescription<{ encode([]: []): string }>;

    requests: TypedFunctionDescription<{ encode([]: [BigNumberish]): string }>;

    getCommitHash: TypedFunctionDescription<{
      encode([epochNumber, voter]: [BigNumberish, string]): string;
    }>;

    parameters: TypedFunctionDescription<{ encode([]: []): string }>;

    slateCount: TypedFunctionDescription<{ encode([]: []): string }>;

    REVEAL_PERIOD_START: TypedFunctionDescription<{ encode([]: []): string }>;

    slateSubmissionPeriodActive: TypedFunctionDescription<{
      encode([resource]: [string]): string;
    }>;

    slateSubmissionDeadline: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    contestDetails: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    epochStart: TypedFunctionDescription<{
      encode([epoch]: [BigNumberish]): string;
    }>;

    EPOCH_LENGTH: TypedFunctionDescription<{ encode([]: []): string }>;

    contestStatus: TypedFunctionDescription<{
      encode([epochNumber, resource]: [BigNumberish, string]): string;
    }>;

    hasPermission: TypedFunctionDescription<{
      encode([requestID]: [BigNumberish]): string;
    }>;

    revealManyBallots: TypedFunctionDescription<{
      encode([epochNumber, _voters, _ballots, _salts]: [
        BigNumberish,
        (string)[],
        (Arrayish)[],
        (BigNumberish)[]
      ]): string;
    }>;

    incumbent: TypedFunctionDescription<{ encode([]: [string]): string }>;

    SLATE_SUBMISSION_PERIOD_START: TypedFunctionDescription<{
      encode([]: []): string;
    }>;

    isCurrentGatekeeper: TypedFunctionDescription<{ encode([]: []): string }>;

    token: TypedFunctionDescription<{ encode([]: []): string }>;

    slates: TypedFunctionDescription<{ encode([]: [BigNumberish]): string }>;

    timeTravel: TypedFunctionDescription<{
      encode([amount]: [BigNumberish]): string;
    }>;

    addToWhitelist: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    removeFromWhitelist: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    isWhitelisted: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;
  };

  events: {
    TimeTraveled: TypedEventDescription<{
      encodeTopics([amount, startTime]: [null, null]): string[];
    }>;

    AddedToWhitelist: TypedEventDescription<{
      encodeTopics([account]: [null]): string[];
    }>;

    RemovedFromWhitelist: TypedEventDescription<{
      encodeTopics([account]: [null]): string[];
    }>;

    PermissionRequested: TypedEventDescription<{
      encodeTopics([epochNumber, resource, requestID, metadataHash]: [
        BigNumberish | null,
        string | null,
        null,
        null
      ]): string[];
    }>;

    SlateCreated: TypedEventDescription<{
      encodeTopics([slateID, recommender, requestIDs, metadataHash]: [
        null,
        string | null,
        null,
        null
      ]): string[];
    }>;

    SlateStaked: TypedEventDescription<{
      encodeTopics([slateID, staker, numTokens]: [null, string | null, null]): string[];
    }>;

    VotingTokensDeposited: TypedEventDescription<{
      encodeTopics([voter, numTokens]: [string | null, null]): string[];
    }>;

    VotingTokensWithdrawn: TypedEventDescription<{
      encodeTopics([voter, numTokens]: [string | null, null]): string[];
    }>;

    VotingRightsDelegated: TypedEventDescription<{
      encodeTopics([voter, delegate]: [string | null, null]): string[];
    }>;

    BallotCommitted: TypedEventDescription<{
      encodeTopics([epochNumber, committer, voter, numTokens, commitHash]: [
        BigNumberish | null,
        string | null,
        string | null,
        null,
        null
      ]): string[];
    }>;

    BallotRevealed: TypedEventDescription<{
      encodeTopics([epochNumber, voter, numTokens]: [
        BigNumberish | null,
        string | null,
        null
      ]): string[];
    }>;

    ContestAutomaticallyFinalized: TypedEventDescription<{
      encodeTopics([epochNumber, resource, winningSlate]: [
        BigNumberish | null,
        string | null,
        null
      ]): string[];
    }>;

    ContestFinalizedWithoutWinner: TypedEventDescription<{
      encodeTopics([epochNumber, resource]: [BigNumberish | null, string | null]): string[];
    }>;

    VoteFinalized: TypedEventDescription<{
      encodeTopics([epochNumber, resource, winningSlate, winnerVotes, totalVotes]: [
        BigNumberish | null,
        string | null,
        null,
        null,
        null
      ]): string[];
    }>;

    VoteFailed: TypedEventDescription<{
      encodeTopics([
        epochNumber,
        resource,
        leadingSlate,
        leaderVotes,
        runnerUpSlate,
        runnerUpVotes,
        totalVotes,
      ]: [BigNumberish | null, string | null, null, null, null, null, null]): string[];
    }>;

    RunoffFinalized: TypedEventDescription<{
      encodeTopics([epochNumber, resource, winningSlate, winnerVotes, losingSlate, loserVotes]: [
        BigNumberish | null,
        string | null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    StakeWithdrawn: TypedEventDescription<{
      encodeTopics([slateID, staker, numTokens]: [null, string | null, null]): string[];
    }>;
  };
}

export class TimeTravelingGatekeeper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): TimeTravelingGatekeeper;
  attach(addressOrName: string): TimeTravelingGatekeeper;
  deployed(): Promise<TimeTravelingGatekeeper>;

  on(event: EventFilter | string, listener: Listener): TimeTravelingGatekeeper;
  once(event: EventFilter | string, listener: Listener): TimeTravelingGatekeeper;
  addListener(eventName: EventFilter | string, listener: Listener): TimeTravelingGatekeeper;
  removeAllListeners(eventName: EventFilter | string): TimeTravelingGatekeeper;
  removeListener(eventName: any, listener: Listener): TimeTravelingGatekeeper;

  interface: TimeTravelingGatekeeperInterface;

  functions: {
    getWinningSlate(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    depositVoteTokens(
      numTokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    slateRequests(slateID: BigNumberish): Promise<(BigNumber)[]>;

    withdrawVoteTokens(
      numTokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdrawStake(
      slateID: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    contestSlates(epochNumber: BigNumberish, resource: string): Promise<(BigNumber)[]>;

    delegateVotingRights(
      _delegate: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getFirstChoiceVotes(
      epochNumber: BigNumberish,
      resource: string,
      slateID: BigNumberish
    ): Promise<BigNumber>;

    requestPermission(
      metadataHash: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    finalizeContest(
      epochNumber: BigNumberish,
      resource: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    voteTokenBalance(arg0: string): Promise<BigNumber>;

    donateChallengerStakes(
      epochNumber: BigNumberish,
      resource: string,
      startIndex: BigNumberish,
      count: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    commitBallot(
      voter: string,
      commitHash: Arrayish,
      numTokens: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    recommendSlate(
      resource: string,
      requestIDs: (BigNumberish)[],
      metadataHash: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    didCommit(epochNumber: BigNumberish, voter: string): Promise<boolean>;

    revealBallot(
      epochNumber: BigNumberish,
      voter: string,
      resources: (string)[],
      firstChoices: (BigNumberish)[],
      secondChoices: (BigNumberish)[],
      salt: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    requestCount(): Promise<BigNumber>;

    delegate(arg0: string): Promise<string>;

    ballots(arg0: BigNumberish): Promise<boolean>;

    getSecondChoiceVotes(
      epochNumber: BigNumberish,
      resource: string,
      slateID: BigNumberish
    ): Promise<BigNumber>;

    currentEpochNumber(): Promise<BigNumber>;

    stakeTokens(
      slateID: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    startTime(): Promise<BigNumber>;

    didReveal(epochNumber: BigNumberish, voter: string): Promise<boolean>;

    COMMIT_PERIOD_START(): Promise<BigNumber>;

    requests(
      arg0: BigNumberish
    ): Promise<{
      metadataHash: string;
      resource: string;
      approved: boolean;
      expirationTime: BigNumber;
      epochNumber: BigNumber;
      0: string;
      1: string;
      2: boolean;
      3: BigNumber;
      4: BigNumber;
    }>;

    getCommitHash(epochNumber: BigNumberish, voter: string): Promise<string>;

    parameters(): Promise<string>;

    slateCount(): Promise<BigNumber>;

    REVEAL_PERIOD_START(): Promise<BigNumber>;

    slateSubmissionPeriodActive(resource: string): Promise<boolean>;

    slateSubmissionDeadline(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    contestDetails(
      epochNumber: BigNumberish,
      resource: string
    ): Promise<{
      status: number;
      allSlates: (BigNumber)[];
      stakedSlates: (BigNumber)[];
      lastStaked: BigNumber;
      voteWinner: BigNumber;
      voteRunnerUp: BigNumber;
      winner: BigNumber;
      0: number;
      1: (BigNumber)[];
      2: (BigNumber)[];
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    epochStart(epoch: BigNumberish): Promise<BigNumber>;

    EPOCH_LENGTH(): Promise<BigNumber>;

    contestStatus(epochNumber: BigNumberish, resource: string): Promise<number>;

    hasPermission(requestID: BigNumberish): Promise<boolean>;

    revealManyBallots(
      epochNumber: BigNumberish,
      _voters: (string)[],
      _ballots: (Arrayish)[],
      _salts: (BigNumberish)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    incumbent(arg0: string): Promise<string>;

    SLATE_SUBMISSION_PERIOD_START(): Promise<BigNumber>;

    isCurrentGatekeeper(): Promise<boolean>;

    token(): Promise<string>;

    slates(
      arg0: BigNumberish
    ): Promise<{
      recommender: string;
      metadataHash: string;
      status: number;
      staker: string;
      stake: BigNumber;
      epochNumber: BigNumber;
      resource: string;
      0: string;
      1: string;
      2: number;
      3: string;
      4: BigNumber;
      5: BigNumber;
      6: string;
    }>;

    timeTravel(
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    addToWhitelist(account: string, overrides?: TransactionOverrides): Promise<ContractTransaction>;

    removeFromWhitelist(
      account: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    isWhitelisted(account: string): Promise<boolean>;
  };

  getWinningSlate(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

  depositVoteTokens(
    numTokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  slateRequests(slateID: BigNumberish): Promise<(BigNumber)[]>;

  withdrawVoteTokens(
    numTokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  withdrawStake(
    slateID: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  contestSlates(epochNumber: BigNumberish, resource: string): Promise<(BigNumber)[]>;

  delegateVotingRights(
    _delegate: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getFirstChoiceVotes(
    epochNumber: BigNumberish,
    resource: string,
    slateID: BigNumberish
  ): Promise<BigNumber>;

  requestPermission(
    metadataHash: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  finalizeContest(
    epochNumber: BigNumberish,
    resource: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  voteTokenBalance(arg0: string): Promise<BigNumber>;

  donateChallengerStakes(
    epochNumber: BigNumberish,
    resource: string,
    startIndex: BigNumberish,
    count: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  commitBallot(
    voter: string,
    commitHash: Arrayish,
    numTokens: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  recommendSlate(
    resource: string,
    requestIDs: (BigNumberish)[],
    metadataHash: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  didCommit(epochNumber: BigNumberish, voter: string): Promise<boolean>;

  revealBallot(
    epochNumber: BigNumberish,
    voter: string,
    resources: (string)[],
    firstChoices: (BigNumberish)[],
    secondChoices: (BigNumberish)[],
    salt: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  requestCount(): Promise<BigNumber>;

  delegate(arg0: string): Promise<string>;

  ballots(arg0: BigNumberish): Promise<boolean>;

  getSecondChoiceVotes(
    epochNumber: BigNumberish,
    resource: string,
    slateID: BigNumberish
  ): Promise<BigNumber>;

  currentEpochNumber(): Promise<BigNumber>;

  stakeTokens(
    slateID: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  startTime(): Promise<BigNumber>;

  didReveal(epochNumber: BigNumberish, voter: string): Promise<boolean>;

  COMMIT_PERIOD_START(): Promise<BigNumber>;

  requests(
    arg0: BigNumberish
  ): Promise<{
    metadataHash: string;
    resource: string;
    approved: boolean;
    expirationTime: BigNumber;
    epochNumber: BigNumber;
    0: string;
    1: string;
    2: boolean;
    3: BigNumber;
    4: BigNumber;
  }>;

  getCommitHash(epochNumber: BigNumberish, voter: string): Promise<string>;

  parameters(): Promise<string>;

  slateCount(): Promise<BigNumber>;

  REVEAL_PERIOD_START(): Promise<BigNumber>;

  slateSubmissionPeriodActive(resource: string): Promise<boolean>;

  slateSubmissionDeadline(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

  contestDetails(
    epochNumber: BigNumberish,
    resource: string
  ): Promise<{
    status: number;
    allSlates: (BigNumber)[];
    stakedSlates: (BigNumber)[];
    lastStaked: BigNumber;
    voteWinner: BigNumber;
    voteRunnerUp: BigNumber;
    winner: BigNumber;
    0: number;
    1: (BigNumber)[];
    2: (BigNumber)[];
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
  }>;

  epochStart(epoch: BigNumberish): Promise<BigNumber>;

  EPOCH_LENGTH(): Promise<BigNumber>;

  contestStatus(epochNumber: BigNumberish, resource: string): Promise<number>;

  hasPermission(requestID: BigNumberish): Promise<boolean>;

  revealManyBallots(
    epochNumber: BigNumberish,
    _voters: (string)[],
    _ballots: (Arrayish)[],
    _salts: (BigNumberish)[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  incumbent(arg0: string): Promise<string>;

  SLATE_SUBMISSION_PERIOD_START(): Promise<BigNumber>;

  isCurrentGatekeeper(): Promise<boolean>;

  token(): Promise<string>;

  slates(
    arg0: BigNumberish
  ): Promise<{
    recommender: string;
    metadataHash: string;
    status: number;
    staker: string;
    stake: BigNumber;
    epochNumber: BigNumber;
    resource: string;
    0: string;
    1: string;
    2: number;
    3: string;
    4: BigNumber;
    5: BigNumber;
    6: string;
  }>;

  timeTravel(amount: BigNumberish, overrides?: TransactionOverrides): Promise<ContractTransaction>;

  addToWhitelist(account: string, overrides?: TransactionOverrides): Promise<ContractTransaction>;

  removeFromWhitelist(
    account: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  isWhitelisted(account: string): Promise<boolean>;

  filters: {
    TimeTraveled(amount: null, startTime: null): EventFilter;

    AddedToWhitelist(account: null): EventFilter;

    RemovedFromWhitelist(account: null): EventFilter;

    PermissionRequested(
      epochNumber: BigNumberish | null,
      resource: string | null,
      requestID: null,
      metadataHash: null
    ): EventFilter;

    SlateCreated(
      slateID: null,
      recommender: string | null,
      requestIDs: null,
      metadataHash: null
    ): EventFilter;

    SlateStaked(slateID: null, staker: string | null, numTokens: null): EventFilter;

    VotingTokensDeposited(voter: string | null, numTokens: null): EventFilter;

    VotingTokensWithdrawn(voter: string | null, numTokens: null): EventFilter;

    VotingRightsDelegated(voter: string | null, delegate: null): EventFilter;

    BallotCommitted(
      epochNumber: BigNumberish | null,
      committer: string | null,
      voter: string | null,
      numTokens: null,
      commitHash: null
    ): EventFilter;

    BallotRevealed(
      epochNumber: BigNumberish | null,
      voter: string | null,
      numTokens: null
    ): EventFilter;

    ContestAutomaticallyFinalized(
      epochNumber: BigNumberish | null,
      resource: string | null,
      winningSlate: null
    ): EventFilter;

    ContestFinalizedWithoutWinner(
      epochNumber: BigNumberish | null,
      resource: string | null
    ): EventFilter;

    VoteFinalized(
      epochNumber: BigNumberish | null,
      resource: string | null,
      winningSlate: null,
      winnerVotes: null,
      totalVotes: null
    ): EventFilter;

    VoteFailed(
      epochNumber: BigNumberish | null,
      resource: string | null,
      leadingSlate: null,
      leaderVotes: null,
      runnerUpSlate: null,
      runnerUpVotes: null,
      totalVotes: null
    ): EventFilter;

    RunoffFinalized(
      epochNumber: BigNumberish | null,
      resource: string | null,
      winningSlate: null,
      winnerVotes: null,
      losingSlate: null,
      loserVotes: null
    ): EventFilter;

    StakeWithdrawn(slateID: null, staker: string | null, numTokens: null): EventFilter;
  };

  estimate: {
    getWinningSlate(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    depositVoteTokens(numTokens: BigNumberish): Promise<BigNumber>;

    slateRequests(slateID: BigNumberish): Promise<BigNumber>;

    withdrawVoteTokens(numTokens: BigNumberish): Promise<BigNumber>;

    withdrawStake(slateID: BigNumberish): Promise<BigNumber>;

    contestSlates(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    delegateVotingRights(_delegate: string): Promise<BigNumber>;

    getFirstChoiceVotes(
      epochNumber: BigNumberish,
      resource: string,
      slateID: BigNumberish
    ): Promise<BigNumber>;

    requestPermission(metadataHash: Arrayish): Promise<BigNumber>;

    finalizeContest(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    voteTokenBalance(arg0: string): Promise<BigNumber>;

    donateChallengerStakes(
      epochNumber: BigNumberish,
      resource: string,
      startIndex: BigNumberish,
      count: BigNumberish
    ): Promise<BigNumber>;

    commitBallot(voter: string, commitHash: Arrayish, numTokens: BigNumberish): Promise<BigNumber>;

    recommendSlate(
      resource: string,
      requestIDs: (BigNumberish)[],
      metadataHash: Arrayish
    ): Promise<BigNumber>;

    didCommit(epochNumber: BigNumberish, voter: string): Promise<BigNumber>;

    revealBallot(
      epochNumber: BigNumberish,
      voter: string,
      resources: (string)[],
      firstChoices: (BigNumberish)[],
      secondChoices: (BigNumberish)[],
      salt: BigNumberish
    ): Promise<BigNumber>;

    requestCount(): Promise<BigNumber>;

    delegate(arg0: string): Promise<BigNumber>;

    ballots(arg0: BigNumberish): Promise<BigNumber>;

    getSecondChoiceVotes(
      epochNumber: BigNumberish,
      resource: string,
      slateID: BigNumberish
    ): Promise<BigNumber>;

    currentEpochNumber(): Promise<BigNumber>;

    stakeTokens(slateID: BigNumberish): Promise<BigNumber>;

    startTime(): Promise<BigNumber>;

    didReveal(epochNumber: BigNumberish, voter: string): Promise<BigNumber>;

    COMMIT_PERIOD_START(): Promise<BigNumber>;

    requests(arg0: BigNumberish): Promise<BigNumber>;

    getCommitHash(epochNumber: BigNumberish, voter: string): Promise<BigNumber>;

    parameters(): Promise<BigNumber>;

    slateCount(): Promise<BigNumber>;

    REVEAL_PERIOD_START(): Promise<BigNumber>;

    slateSubmissionPeriodActive(resource: string): Promise<BigNumber>;

    slateSubmissionDeadline(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    contestDetails(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    epochStart(epoch: BigNumberish): Promise<BigNumber>;

    EPOCH_LENGTH(): Promise<BigNumber>;

    contestStatus(epochNumber: BigNumberish, resource: string): Promise<BigNumber>;

    hasPermission(requestID: BigNumberish): Promise<BigNumber>;

    revealManyBallots(
      epochNumber: BigNumberish,
      _voters: (string)[],
      _ballots: (Arrayish)[],
      _salts: (BigNumberish)[]
    ): Promise<BigNumber>;

    incumbent(arg0: string): Promise<BigNumber>;

    SLATE_SUBMISSION_PERIOD_START(): Promise<BigNumber>;

    isCurrentGatekeeper(): Promise<BigNumber>;

    token(): Promise<BigNumber>;

    slates(arg0: BigNumberish): Promise<BigNumber>;

    timeTravel(amount: BigNumberish): Promise<BigNumber>;

    addToWhitelist(account: string): Promise<BigNumber>;

    removeFromWhitelist(account: string): Promise<BigNumber>;

    isWhitelisted(account: string): Promise<BigNumber>;
  };
}
